apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
parameters:
  targetTrAddr: {{ .Values.storageClass.parameters.targetTrAddr | quote }}
  targetTrPort: {{ .Values.storageClass.parameters.targetTrPort | quote }}
  targetTrType: {{ .Values.storageClass.parameters.targetTrType | quote }}
provisioner: csi.nvmf.com
reclaimPolicy: Delete
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}